### ISSUE TITLE
Word count inaccurate for longer documents

### ISSUE THREAD

**Issue by wmbenedetto** [lukeleppan/better-word-count#10]
I haven't been able to pinpoint any particular reason this is happening, but I'm finding that this plugin is generally over-counting by a few percent in the total word count. 

For example, a document listed at 6,959 words with your plugin is only 6,812 in other editors. One that is 14,817 words in Obsidian is only 14,220 in other editors. 

This is an issue for me, since I write fiction which is usually targeted at specific word limits. I worked really hard to get that 6,959 word story under 7,000 words, only to discover that I could have kept about 200 words more than I ended up cutting, since the actual count was really 6,812.

I'm happy to share one of the documents in question, if that will help with troubleshooting.

**Comment by lukeleppan** [comment]
Hi thanks the feedback. Sorry this is happening to you. 

So over obsidian's development the default word count algorithm has changed many times. I have tried to keep the one I use the same as their one. 

I think, the latest version is the same as Microsoft Word's algorithm.

If you could send that document it would help me see if it's an issue or just due to the difference in algorithms.

Could you compare the better word count to the default one in obsidian? If they are the same it probably means that your other text editor uses a different algorithm, then I can't really change it since I would like to keep it the same as the default. 

Also if you're interested, you might want to look at the different ways that words are counted. Some algorithms count numbers as words and some don't well as differences in how hyphenated words are counted. So sometimes the discrepancies can end up quite large between different algorithms. I'm not sure if you're writing for fun or for scholarly reasons. But the institution you may be writing for might have a certain standard that you need to follow.

Thank you.

**Comment by wmbenedetto** [comment]
Wow, I didn't realize the algorithms could vary so widely. I dropped my text into various online word counters just out of curiosity, and they range from ~6,500 to ~6,800 words. It seems like your plugin is particularly "generous" in the counting compared to the others (at 6959), but I'm surprised to see how much variance there it. Your word count is the same as the Obsidian default, so if that's the intention, then it's working as expected.
