### ISSUE TITLE
Feature request: Count only text shown in preview

### ISSUE THREAD

**Issue by faithwicca** [lukeleppan/better-word-count#27]
Now if you use a link like this [text](https://www.something...) what is counted is everything including brackets and the link in the brackets itself. It would be really useful, if there was an option to show only the count of characters of "text", since only it is shown in preview.

**Comment by lukeleppan** [comment]
Should be working nicely with live preview in the latest update.

**Comment by amzon-ex** [comment]
Hi, I don't think this works. Different parts of links continue to be counted as words. For long links, this adds extremely high overhead to the actual count.

**Comment by lukeleppan** [comment]
Yes, I was wrong. I will reopen this. "Sanitation" option like this will be implemented but by bit. However this is quite a difficult one, since blocks from other notes can be expanded within preview. One thing that will be implemented is markdown sanitation which will remove all markdown syntax before counting.
