### ISSUE TITLE
Won't load after update 

### ISSUE THREAD

**Issue by ReaderGuy42** [lukeleppan/better-word-count#42]
I just updated the plugin, since I saw you had a new commit (release?) https://github.com/lukeleppan/better-word-count/commit/3434a4f145c52a112a077955bca38aa9ab551232

But now the plugin won't load at all, and get the error `Failed to load Plugin` and this is in the console:
![image](https://user-images.githubusercontent.com/71895400/155533172-67c04c32-2824-48f1-b1df-8ac507ed1073.png)

I'm on Linux Mint, Obsidian v0.13.23 (Installer v0.12.15)

Thanks :)

**Comment by tmmmmm** [comment]
Are you using the Legacy Editor? It says it on top of the Readme:

`IMPORTANT NOTICE: Due to the introduction of the new Live Preview feature, this plugin needed to be almost entirely rewritten. Currently the plugin only displays the only the word and character count with selecting text features. ALL other features have been scrapped and will be ported in future updates. DO NOT UPDATE If you want to use the legacy editor since their is no backwards compatibility yet (I know I'm lazy but I wanted to release the fix, its been too long).`

**Comment by ReaderGuy42** [comment]
I'm not :) Thanks though!

**Comment by ReaderGuy42** [comment]
the newest release 0.8.1 works now! But there's no settings to change the default appearance, but I assume that'll come later. Thanks for the quick fix!!
