### ISSUE TITLE
Support for non-latin (e.g. cyrillic) scripts

### ISSUE THREAD

**Issue by approximate** [lukeleppan/better-word-count#8]
Hi @lukeleppan, thanks for the great plugin! 
Do you plan to support non-latin scripts?

**Comment by lukeleppan** [comment]
Yes that has been something I have been considering. I think it's very important but I'll have to do some research to figure out how to implement it. Currently I'm busy with other projects (studies). But I do plan to implement other language support. As well as a few more advanced features and statistics in the future. The multi language support is my main concern, so that will be in the next update hopefully. But yes it will be a couple weeks before I maybe to work on it. Sorry for the wait.

**Comment by lukeleppan** [comment]
Ok it's done, ignore that. Update the plugin. It should be working. Thank you!

**Comment by approximate** [comment]
Seems to work, thanks a ton for such a quick turnaround!
